name = "my-cloudflare-project"
main = "src/index.ts"
compatibility_date = "2023-04-05"


account_id = "baaf5942cef0e85249213892f313787d"
workers_dev = true
kv_namespaces = [
    { binding = "MY_NAMESPACE", id = "dd3bc326a39c4d8e9e1c4dc2bd9eb68b", preview_id = "a980d9f2c6cd47cca27457d0517156a0" }
]